// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "license": {
            "name": "MIT",
            "url": "https://opensource.org/licenses/MIT"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/comments": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "comments"
                ],
                "summary": "Создание комментария",
                "operationId": "createComment",
                "parameters": [
                    {
                        "description": "Comment data",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/web.CommentCreate"
                        }
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/web.ErrorResponseStruct"
                        }
                    },
                    "401": {
                        "description": "Unauthorized"
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/web.ErrorResponseStruct"
                        }
                    }
                }
            }
        },
        "/comments/{id}": {
            "delete": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "comments"
                ],
                "summary": "Удаление комментария",
                "operationId": "deleteComment",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Comment` + "`" + `s id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/web.ErrorResponseStruct"
                        }
                    },
                    "401": {
                        "description": "Unauthorized"
                    },
                    "403": {
                        "description": "Forbidden"
                    },
                    "404": {
                        "description": "Not Found"
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/web.ErrorResponseStruct"
                        }
                    }
                }
            },
            "patch": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "comments"
                ],
                "summary": "Обновление информации о комментарии",
                "operationId": "updateComment",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Comment` + "`" + `s id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Comment data",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/web.CommentUpdate"
                        }
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/web.ErrorResponseStruct"
                        }
                    },
                    "401": {
                        "description": "Unauthorized"
                    },
                    "403": {
                        "description": "Forbidden"
                    },
                    "404": {
                        "description": "Not Found"
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/web.ErrorResponseStruct"
                        }
                    }
                }
            }
        },
        "/ingredients": {
            "get": {
                "description": "Получение списка ингредиентов",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "ingredients"
                ],
                "summary": "Получение ингредиентов",
                "operationId": "getIngredientsByPage",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Page number",
                        "name": "page",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/v2.IngredientsResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/web.ErrorResponseStruct"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/web.ErrorResponseStruct"
                        }
                    }
                }
            }
        },
        "/ingredients/{id}": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "ingredients"
                ],
                "summary": "Получение ингредиентов, использующихся в рецепте",
                "operationId": "getRecipeIngredients",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Recipe` + "`" + `s id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/v2.IngredientsResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/web.ErrorResponseStruct"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/web.ErrorResponseStruct"
                        }
                    }
                }
            }
        },
        "/login": {
            "post": {
                "description": "Метод для получения bearer-токена",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "users"
                ],
                "summary": "Аутентификация",
                "operationId": "login",
                "parameters": [
                    {
                        "description": "Login data",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/web.LoginReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/web.SuccessResponseStruct"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/web.ErrorResponseStruct"
                        }
                    }
                }
            }
        },
        "/measurements": {
            "get": {
                "description": "Получение списка всех доступных единиц измерения",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "measurements"
                ],
                "summary": "Получение списка единиц измерения",
                "operationId": "getAllMeasurements",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/v2.MeasurementsResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/web.ErrorResponseStruct"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/web.ErrorResponseStruct"
                        }
                    }
                }
            }
        },
        "/measurements/{id}": {
            "get": {
                "description": "Получение единицы измерения ингредиента, использующегося в рецепте",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "measurements"
                ],
                "summary": "Получение единицы измерения ингредиента",
                "operationId": "getIngredientMeasurement",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Recipe` + "`" + `s id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Ingredient` + "`" + `s id",
                        "name": "ingredient",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/v2.MeasurementResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/web.ErrorResponseStruct"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/web.ErrorResponseStruct"
                        }
                    }
                }
            }
        },
        "/recipeSteps": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "recipeSteps"
                ],
                "summary": "Создание шага рецепта",
                "operationId": "createRecipeStep",
                "parameters": [
                    {
                        "description": "Recipe step data",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/web.RecipeStepCreate"
                        }
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/web.ErrorResponseStruct"
                        }
                    },
                    "401": {
                        "description": "Unauthorized"
                    },
                    "403": {
                        "description": "Forbidden"
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/web.ErrorResponseStruct"
                        }
                    }
                }
            }
        },
        "/recipeSteps/{id}": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "recipeSteps"
                ],
                "summary": "Получение шагов рецепта",
                "operationId": "getRecipeSteps",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Recipe` + "`" + `s id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/v2.RecipeStepsResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/web.ErrorResponseStruct"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/web.ErrorResponseStruct"
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "recipeSteps"
                ],
                "summary": "Удаление шага рецепта",
                "operationId": "deleteRecipeStep",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Recipe step` + "`" + `s id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/web.ErrorResponseStruct"
                        }
                    },
                    "401": {
                        "description": "Unauthorized"
                    },
                    "403": {
                        "description": "Forbidden"
                    },
                    "404": {
                        "description": "Not Found"
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/web.ErrorResponseStruct"
                        }
                    }
                }
            },
            "patch": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "recipeSteps"
                ],
                "summary": "Обновление информации о шаге рецепта",
                "operationId": "updateRecipeStep",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Recipe step` + "`" + `s id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Recipe data",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/web.RecipeStepUpdate"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/web.RecipeStep"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/web.ErrorResponseStruct"
                        }
                    },
                    "401": {
                        "description": "Unauthorized"
                    },
                    "403": {
                        "description": "Forbidden"
                    },
                    "404": {
                        "description": "Not Found"
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/web.ErrorResponseStruct"
                        }
                    }
                }
            }
        },
        "/recipes": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "recipes"
                ],
                "summary": "Создание рецепта",
                "operationId": "createRecipe",
                "parameters": [
                    {
                        "description": "Recipe data",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/web.RecipeCreate"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/v2.RecipeResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/web.ErrorResponseStruct"
                        }
                    },
                    "401": {
                        "description": "Unauthorized"
                    },
                    "403": {
                        "description": "Forbidden"
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/web.ErrorResponseStruct"
                        }
                    }
                }
            }
        },
        "/recipes/{id}": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "recipes"
                ],
                "summary": "Получение информации о салате",
                "operationId": "getRecipe",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Salad` + "`" + `s id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/v2.RecipeResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/web.ErrorResponseStruct"
                        }
                    },
                    "404": {
                        "description": "Not Found"
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/web.ErrorResponseStruct"
                        }
                    }
                }
            },
            "patch": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "recipes"
                ],
                "summary": "Обновление информации о рецепте",
                "operationId": "updateRecipe",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Recipe` + "`" + `s id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Recipe data",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/web.RecipeUpdate"
                        }
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/web.ErrorResponseStruct"
                        }
                    },
                    "401": {
                        "description": "Unauthorized"
                    },
                    "403": {
                        "description": "Forbidden"
                    },
                    "404": {
                        "description": "Not Found"
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/web.ErrorResponseStruct"
                        }
                    }
                }
            }
        },
        "/register": {
            "post": {
                "description": "Метод для регистрации",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "users"
                ],
                "summary": "Регистрация",
                "operationId": "signup",
                "parameters": [
                    {
                        "description": "Register data",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/web.RegisterReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/web.SuccessResponseStruct"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/web.ErrorResponseStruct"
                        }
                    }
                }
            }
        },
        "/salads": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Получение списка салатов по указанным фильтрам",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "salads"
                ],
                "summary": "Получение салатов",
                "operationId": "getSalads",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Page number",
                        "name": "page",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "number",
                        "description": "Minimal rating of salad to filter",
                        "name": "minRate",
                        "in": "query"
                    },
                    {
                        "type": "array",
                        "items": {
                            "type": "string"
                        },
                        "collectionFormat": "multi",
                        "description": "Available ingredients to filter",
                        "name": "ingredients",
                        "in": "query"
                    },
                    {
                        "type": "array",
                        "items": {
                            "type": "string"
                        },
                        "collectionFormat": "multi",
                        "description": "Available salad types to filter",
                        "name": "types",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Status of salad (only for admins)",
                        "name": "status",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/v2.SaladsResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/web.ErrorResponseStruct"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/web.ErrorResponseStruct"
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "salads"
                ],
                "summary": "Создание салата",
                "operationId": "creteSalad",
                "parameters": [
                    {
                        "description": "Salad data",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/web.SaladCreate"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/v2.SaladResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/web.ErrorResponseStruct"
                        }
                    },
                    "401": {
                        "description": "Unauthorized"
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/web.ErrorResponseStruct"
                        }
                    }
                }
            }
        },
        "/salads/{id}": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "salads"
                ],
                "summary": "Получение информации о салате",
                "operationId": "getSalad",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Salad` + "`" + `s id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/v2.SaladResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/web.ErrorResponseStruct"
                        }
                    },
                    "404": {
                        "description": "Not Found"
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/web.ErrorResponseStruct"
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "salads"
                ],
                "summary": "Удаление информации о салате",
                "operationId": "deleteSalad",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Salad` + "`" + `s id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/web.ErrorResponseStruct"
                        }
                    },
                    "401": {
                        "description": "Unauthorized"
                    },
                    "403": {
                        "description": "Forbidden"
                    },
                    "404": {
                        "description": "Not Found"
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/web.ErrorResponseStruct"
                        }
                    }
                }
            },
            "patch": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "salads"
                ],
                "summary": "Обновление информации о салате",
                "operationId": "updateSalad",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Salad` + "`" + `s id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Salad data",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/web.SaladUpdate"
                        }
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/web.ErrorResponseStruct"
                        }
                    },
                    "401": {
                        "description": "Unauthorized"
                    },
                    "403": {
                        "description": "Forbidden"
                    },
                    "404": {
                        "description": "Not Found"
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/web.ErrorResponseStruct"
                        }
                    }
                }
            }
        },
        "/salads/{id}/comments": {
            "get": {
                "description": "Получение списка комментариев",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "comments"
                ],
                "summary": "Получение комментариев",
                "operationId": "getComments",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Salad's id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "Page",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "User's id",
                        "name": "user_id",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/v2.CommentsResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/web.ErrorResponseStruct"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/web.ErrorResponseStruct"
                        }
                    }
                }
            }
        },
        "/salads/{id}/ingredients": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "ingredients"
                ],
                "summary": "Добавление ингредиента к рецепту",
                "operationId": "linkIngredient",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Salad` + "`" + `s id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Link data",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/web.LinkIngredientSalad"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/v2.LinkIngredientSaladResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/web.ErrorResponseStruct"
                        }
                    },
                    "401": {
                        "description": "Unauthorized"
                    },
                    "403": {
                        "description": "Forbidden"
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/web.ErrorResponseStruct"
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "ingredients"
                ],
                "summary": "Удаление ингредиента из рецепта",
                "operationId": "unlinkIngredient",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Salad` + "`" + `s id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Link data",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/web.LinkIngredientSalad"
                        }
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/web.ErrorResponseStruct"
                        }
                    },
                    "401": {
                        "description": "Unauthorized"
                    },
                    "403": {
                        "description": "Forbidden"
                    },
                    "404": {
                        "description": "Not Found"
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/web.ErrorResponseStruct"
                        }
                    }
                }
            }
        },
        "/salads/{id}/types": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "types"
                ],
                "summary": "Получение типов салата",
                "operationId": "getSaladTypes",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Salad` + "`" + `s id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/v2.IngredientsResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/web.ErrorResponseStruct"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/web.ErrorResponseStruct"
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "types"
                ],
                "summary": "Добавление типа к салату",
                "operationId": "linkType",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Salad` + "`" + `s id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Link data",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/web.LinkSaladType"
                        }
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/web.ErrorResponseStruct"
                        }
                    },
                    "401": {
                        "description": "Unauthorized"
                    },
                    "403": {
                        "description": "Forbidden"
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/web.ErrorResponseStruct"
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "types"
                ],
                "summary": "Удаление привязки типа к салату",
                "operationId": "unlinkType",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Salad` + "`" + `s id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Link data",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/web.LinkSaladType"
                        }
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/web.ErrorResponseStruct"
                        }
                    },
                    "401": {
                        "description": "Unauthorized"
                    },
                    "403": {
                        "description": "Forbidden"
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/web.ErrorResponseStruct"
                        }
                    }
                }
            }
        },
        "/types": {
            "get": {
                "description": "Получение списка типов салатов",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "types"
                ],
                "summary": "Получение типов салатов",
                "operationId": "getSaladTypesByPage",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Page number",
                        "name": "page",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/v2.AllSaladTypesResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/web.ErrorResponseStruct"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/web.ErrorResponseStruct"
                        }
                    }
                }
            }
        },
        "/users/me/salads": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Получение списка салатов авторизованного пользователя",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "salads"
                ],
                "summary": "Получение салатов пользователя",
                "operationId": "getUserSalads",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Page number",
                        "name": "page",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "boolean",
                        "description": "Show salads rated by user",
                        "name": "onlyRated",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/v2.SaladsResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/web.ErrorResponseStruct"
                        }
                    },
                    "401": {
                        "description": "Unauthorized"
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/web.ErrorResponseStruct"
                        }
                    }
                }
            }
        },
        "/users/{id}": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Метод для получения информации о пользователе",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "users"
                ],
                "summary": "Информация о пользователе",
                "operationId": "getUser",
                "parameters": [
                    {
                        "type": "string",
                        "description": "User` + "`" + `s id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/v2.UserResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/web.ErrorResponseStruct"
                        }
                    },
                    "401": {
                        "description": "Unauthorized"
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/web.ErrorResponseStruct"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "mail.Address": {
            "type": "object",
            "properties": {
                "address": {
                    "description": "user@domain",
                    "type": "string"
                },
                "name": {
                    "description": "Proper name; may be empty.",
                    "type": "string"
                }
            }
        },
        "v2.AllSaladTypesResponse": {
            "type": "object",
            "properties": {
                "num_pages": {
                    "type": "integer"
                },
                "salads": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/web.Salad"
                    }
                }
            }
        },
        "v2.CommentsResponse": {
            "type": "object",
            "properties": {
                "comments": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/web.Comment"
                    }
                },
                "num_pages": {
                    "type": "integer"
                }
            }
        },
        "v2.IngredientsResponse": {
            "type": "object",
            "properties": {
                "step": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/web.Ingredient"
                    }
                }
            }
        },
        "v2.LinkIngredientSaladResponse": {
            "type": "object",
            "properties": {
                "link_id": {
                    "type": "string"
                }
            }
        },
        "v2.MeasurementResponse": {
            "type": "object",
            "properties": {
                "count": {
                    "type": "integer"
                },
                "measurement": {
                    "$ref": "#/definitions/web.Measurement"
                }
            }
        },
        "v2.MeasurementsResponse": {
            "type": "object",
            "properties": {
                "measurements": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/web.Measurement"
                    }
                }
            }
        },
        "v2.RecipeResponse": {
            "type": "object",
            "properties": {
                "recipe": {
                    "$ref": "#/definitions/web.Recipe"
                }
            }
        },
        "v2.RecipeStepsResponse": {
            "type": "object",
            "properties": {
                "step": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/web.RecipeStep"
                    }
                }
            }
        },
        "v2.SaladResponse": {
            "type": "object",
            "properties": {
                "salad": {
                    "$ref": "#/definitions/web.Salad"
                }
            }
        },
        "v2.SaladsResponse": {
            "type": "object",
            "properties": {
                "num_pages": {
                    "type": "integer"
                },
                "salads": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/web.Salad"
                    }
                }
            }
        },
        "v2.UserResponse": {
            "type": "object",
            "properties": {
                "user": {
                    "$ref": "#/definitions/web.User"
                }
            }
        },
        "web.Comment": {
            "type": "object",
            "properties": {
                "author_id": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "rating": {
                    "type": "integer"
                },
                "salad_id": {
                    "type": "string"
                },
                "text": {
                    "type": "string"
                }
            }
        },
        "web.CommentCreate": {
            "type": "object",
            "properties": {
                "rating": {
                    "type": "integer"
                },
                "salad_id": {
                    "type": "string"
                },
                "text": {
                    "type": "string"
                }
            }
        },
        "web.CommentUpdate": {
            "type": "object",
            "properties": {
                "rating": {
                    "type": "integer"
                },
                "text": {
                    "type": "string"
                }
            }
        },
        "web.ErrorResponseStruct": {
            "type": "object",
            "properties": {
                "error": {
                    "type": "string"
                },
                "status": {
                    "type": "string"
                }
            }
        },
        "web.Ingredient": {
            "type": "object",
            "properties": {
                "calories": {
                    "type": "integer"
                },
                "id": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "type_id": {
                    "type": "string"
                }
            }
        },
        "web.LinkIngredientSalad": {
            "type": "object",
            "properties": {
                "amount": {
                    "type": "integer"
                },
                "ingredient_id": {
                    "type": "string"
                },
                "measurement_id": {
                    "type": "string"
                },
                "recipe_id": {
                    "type": "string"
                },
                "salad_id": {
                    "type": "string"
                }
            }
        },
        "web.LinkSaladType": {
            "type": "object",
            "properties": {
                "salad_id": {
                    "type": "string"
                },
                "type_id": {
                    "type": "string"
                }
            }
        },
        "web.LoginReq": {
            "type": "object",
            "properties": {
                "login": {
                    "type": "string"
                },
                "password": {
                    "type": "string"
                }
            }
        },
        "web.Measurement": {
            "type": "object",
            "properties": {
                "grams": {
                    "type": "integer"
                },
                "id": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                }
            }
        },
        "web.Recipe": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "string"
                },
                "number_of_servings": {
                    "type": "integer"
                },
                "rating": {
                    "type": "number"
                },
                "salad_id": {
                    "type": "string"
                },
                "status": {
                    "type": "integer"
                },
                "time_to_cook": {
                    "type": "integer"
                }
            }
        },
        "web.RecipeCreate": {
            "type": "object",
            "properties": {
                "number_of_servings": {
                    "type": "integer"
                },
                "salad_id": {
                    "type": "string"
                },
                "time_to_cook": {
                    "type": "integer"
                }
            }
        },
        "web.RecipeStep": {
            "type": "object",
            "properties": {
                "description": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "recipe_id": {
                    "type": "string"
                },
                "step_num": {
                    "type": "integer"
                }
            }
        },
        "web.RecipeStepCreate": {
            "type": "object",
            "properties": {
                "description": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "recipe_id": {
                    "type": "string"
                }
            }
        },
        "web.RecipeStepUpdate": {
            "type": "object",
            "properties": {
                "description": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "step_num": {
                    "type": "integer"
                }
            }
        },
        "web.RecipeUpdate": {
            "type": "object",
            "properties": {
                "number_of_servings": {
                    "type": "integer"
                },
                "status": {
                    "type": "integer"
                },
                "time_to_cook": {
                    "type": "integer"
                }
            }
        },
        "web.RegisterReq": {
            "type": "object",
            "properties": {
                "email": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "password": {
                    "type": "string"
                },
                "username": {
                    "type": "string"
                }
            }
        },
        "web.Salad": {
            "type": "object",
            "properties": {
                "author_id": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                }
            }
        },
        "web.SaladCreate": {
            "type": "object",
            "properties": {
                "description": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                }
            }
        },
        "web.SaladUpdate": {
            "type": "object",
            "properties": {
                "description": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                }
            }
        },
        "web.SuccessResponseStruct": {
            "type": "object",
            "properties": {
                "data": {},
                "status": {
                    "type": "string"
                }
            }
        },
        "web.User": {
            "type": "object",
            "properties": {
                "email": {
                    "$ref": "#/definitions/mail.Address"
                },
                "id": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "role": {
                    "type": "string"
                },
                "username": {
                    "type": "string"
                }
            }
        }
    },
    "securityDefinitions": {
        "BearerAuth": {
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8081",
	BasePath:         "/api/v2",
	Schemes:          []string{},
	Title:            "Сервис поиска рецептов салатов",
	Description:      "Сервис призван помочь с поиском рецептов.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
